### ISSUE TITLE
【阵营沙盘】沙盘补充介绍与攻略

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvp#10]
## 加载沙盘指南

可以弄成多个tab

https://cms.jx3box.com/api/cms/post/56294

```

import {$cms} from '@jx3box/jx3box-common/js/https_v2.js

$cms().get(`/api/cms/post/${id}`)



```

- [ ] 已完成

**Comment by iRuxu** [comment]
## 加载小攻防的攻略

https://cms.jx3box.com/api/cms/posts?type=bps&per=10&page=1&order=update&client=std&topic=%E5%B0%8F%E6%94%BB%E9%98%B2


- [ ] 已完成

**Comment by iRuxu** [comment]
## 沙盘记录
<img width="263" alt="image" src="https://user-images.githubusercontent.com/8476969/225930688-02357aba-0b4c-4890-9685-279a832804b4.png">

- [ ] 已完成

**Comment by 1134617484** [comment]
完成：https://github.com/JX3BOX/pvp/pull/15
