### ISSUE TITLE
竞技技巧详情页

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvp#28]
## 跳转
发布完成要跳转
https://www.jx3box.com/pvp/?subtype=%E6%AF%92%E7%BB%8F

- [x] 已完成

**Comment by iRuxu** [comment]
## 布局有问题
<img width="993" alt="image" src="https://user-images.githubusercontent.com/8476969/231767331-33a6a9e3-32c5-449e-a7cc-428c807e0846.png">

- [ ] 已完成

**Comment by iRuxu** [comment]
## 打赏与评论

<img width="1356" alt="image" src="https://user-images.githubusercontent.com/8476969/231768828-2884e961-c394-4304-9d0d-dbc9b725d490.png">

- [ ] 已完成

**Comment by ghn9264** [comment]
竞技技巧中，技能连招目前只能增加增加，不能删除。

**Comment by ghn9264** [comment]
目前这个新增技能的操作有点过于复杂，优化建议：
点击新增技能后，打开一个编辑界面，上半部分是毒经的武学面板，下半部分是排版中的技能。新增技能的操作方式：
1、点击武学面板对应的技能后，在下半部分依次添加该技能，该技能右上角显示x号可删除。（略过了搜索操作，提高效率）
2、保留当前搜索的添加方式，但搜索完成后，也是先将技能放置在下半部分排版区，同样显示x号可删除。（用于特殊情况下，添加一些非本门派的技能）
3、点击完成排版后回到主界面。
