### ISSUE TITLE
武学研习面板细节完善

### ISSUE THREAD

**Issue by ghn9264** [JX3BOX/pvp#29]
![image](https://user-images.githubusercontent.com/32256957/231793260-00d250d5-99cf-48dc-83c5-64851cc3a005.png)

**Comment by ghn9264** [comment]
奇穴模拟器的默认版本应改为当前使用的版本，而不是体服版本

**Comment by ghn9264** [comment]
完善百科前的文字提示修改显示逻辑：
1、刚点进页面提示：请在面板选择要查看的技能。
2、点击后显示：
无内容》当前技能暂无百科，我要完善
有内容》技能百科内容

**Comment by ghn9264** [comment]
特殊技能文字修改：特殊技能四个字修改为【技能分类】
显示逻辑修改为：默认折叠。（最好可以展示分类，具体分类下的内容折叠）

**Comment by ghn9264** [comment]
武学分享点赞等按钮最好放到头像下面，目前的位置容易被忽视，整体布局可以调整一下。

**Comment by iRuxu** [comment]
> ![image](https://user-images.githubusercontent.com/32256957/231793260-00d250d5-99cf-48dc-83c5-64851cc3a005.png)

补天的切换过去再看
奇穴的展开可以看
以上2个不改

## 右侧奇穴的pop
通过左侧拿到奇穴模拟器数据后，直接将对应数据加载到store中，然后通过store里匹配id去拿然后展示吧。

## 奇穴描述
增加html支持，简单渲染v-html即可

- [ ] 已完成

**Comment by iRuxu** [comment]
> 奇穴模拟器的默认版本应改为当前使用的版本，而不是体服版本

由运营前往后台配置
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/8476969/232231126-97988e4b-9c30-465a-80b2-ef23babfba67.png">
具体版本号通过下方查看
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/8476969/232231077-1d56dd20-d18f-423f-851c-29a78c3eee0a.png">

然后开发请求自己的面包屑接口，如果有设置，则使用对应设置的，
如果接口异常或为空，则使用最新的一个版本

- [ ] 已完成

**Comment by iRuxu** [comment]
> 完善百科前的文字提示修改显示逻辑： 1、刚点进页面提示：请在面板选择要查看的技能。 2、点击后显示： 无内容》当前技能暂无百科，我要完善 有内容》技能百科内容

中肯

- [ ] 已完成

**Comment by iRuxu** [comment]
> 特殊技能文字修改：特殊技能四个字修改为【技能分类】 显示逻辑修改为：默认折叠。（最好可以展示分类，具体分类下的内容折叠）

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/8476969/232231321-603f7290-b7ec-438e-9a70-81e6a10f7a0c.png">

- [ ] 已完成

**Comment by iRuxu** [comment]
## 打赏投币额度
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/8476969/232272387-5a87cccb-744d-41fa-a3c3-b3771bc31089.png">

这里应该有加载一个接口的，是有不同额度的

- [ ] 已完成

**Comment by iRuxu** [comment]
## 打赏记录
<img width="429" alt="image" src="https://user-images.githubusercontent.com/8476969/232272419-c420d17e-22e9-4897-942e-dece75dd6a78.png">

抽屉不对

- [ ] 已完成

**Comment by iRuxu** [comment]
## popover
