### ISSUE TITLE
武学研习优化

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvp#36]
## 特殊技能

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/8476969/234305401-a160322d-2c95-4bb4-a658-d3978ba40859.png">

- [x] 已完成

**Comment by iRuxu** [comment]
## 特殊技能
<img width="742" alt="image" src="https://user-images.githubusercontent.com/8476969/234338385-1b8c528b-624e-4430-9b36-95505ba6940c.png">

<img width="676" alt="image" src="https://user-images.githubusercontent.com/8476969/234338592-5298d9b5-fc36-4479-a580-fc012361b1a4.png">
技能合集是对的

- [ ] 已完成

**Comment by ghn9264** [comment]
![image](https://user-images.githubusercontent.com/32256957/234466820-a8b439c5-e0b4-4141-9441-658302807ba1.png)

**Comment by ghn9264** [comment]
![image](https://user-images.githubusercontent.com/32256957/234467847-2c4c44a2-79d9-4ea1-b812-41389918c511.png)
