### ISSUE TITLE
【武学研习】功能优化

### ISSUE THREAD

**Issue by ghn9264** [JX3BOX/pvp#37]

**Comment by ghn9264** [comment]
![image](https://github.com/JX3BOX/pvp/assets/32256957/3c489fc4-9012-4201-92e8-18d18af1261f)
竞技场热门按心法排，分为dps和奶。可按数据集设置，例如获取的数据为
dps——
{
  bingxin: 3,
  huajian: 4,
  dujing: 7,
  mowen: 14,
  wufang: 1,
  aoxue: 5,
  yijin: 11,
  fenying: 1,
  fenshan: 2,
  zixia: 8,
  taixu: 4,
  tianluo: 7,
  jingyu: 9,
  cangjian: 1,
  xiaochen: 5,
  beiao: 8,
  linghai: 4,
  yinlong: 11,
  taixuan: 7,
  gufeng: 34,
  undefined: 0
}
hps——
 { yunshang: 14, butian: 10, lijing: 14, xiangzhi: 9, lingsu: 7 } 
——
total 200

**Comment by iRuxu** [comment]
具体和产品沟通

**Comment by ghn9264** [comment]
![image](https://github.com/JX3BOX/pvp/assets/32256957/b6aaf44c-3561-440b-984d-c3e335befb69)
奇穴模拟器的这部分搬到
![image](https://github.com/JX3BOX/pvp/assets/32256957/3ae80468-21ac-4d56-89b3-e4b9bcb36941)
这个位置，可随时修改。

**Comment by Kaviilee** [comment]
> ![image](https://user-images.githubusercontent.com/32256957/241379888-b6aaf44c-3561-440b-984d-c3e335befb69.png) 奇穴模拟器的这部分搬到 ![image](https://user-images.githubusercontent.com/32256957/241379941-3ae80468-21ac-4d56-89b3-e4b9bcb36941.png) 这个位置，可随时修改。

该功能会增加维护成本和导致发布中心的库非常臃肿，不考虑将奇穴模拟器搬迁到发布中心，直接去模拟器去复制就好了
