### ISSUE TITLE
绝境战场版面设计稿

### ISSUE THREAD

**Issue by ghn9264** [JX3BOX/pvp#38]
![image](https://github.com/JX3BOX/pvp/assets/32256957/82fbe73c-cd7a-49ec-9b0e-b6d884100970)
左下角应用增加一个怀旧服掉落技能查询

**Comment by ghn9264** [comment]
https://js.design/f/EV3yXx?p=3RrnXe 设计稿链接

**Comment by ghn9264** [comment]
方案二：
将地图做成板块样式，例如绝境战场分为以下板块： 楼兰，银沙石林孔雀海鸣沙山，玉门响马飞沙，遗迹，青岚碎风，血衣，乌孙祭坛
鼠标移动到指定板块会有描边特效，点进去是玩家对该区域的一些点评。

**Comment by ghn9264** [comment]
绝境战场地图功能需求
1. 功能描述
玩家可在吃鸡地图上标记点位并浏览点位附带的短评。

2. 用户故事
小张是一个吃鸡老手，喜欢分享自己的一些吃鸡心得，于是他在魔盒绝境战场地图上用红圈标记了地图上物资丰富的地方，用蓝圈标记了相对丰富，但比较安全的地方，并用橙圈标记了线路的起点，附上短评，说这条线去地图上哪个物资丰富的区域是最快的，建议落点在哪等短评信息。
小王是一个吃鸡新手，他不知道吃鸡的时候在线路上哪个地点跳，以及转战什么地方可以捡到很多物资，于是他上魔盒绝境战场这个应用查看资源分布图及吃鸡路线建议落点。

3. 用户操作
标点：选择三种标记工具：1、大量资源（红色圈） 2、少了资源（蓝色圈） 3、路线建议（橙色圈） ，在地图上对应位置点击生成圈，弹出短评对话框，填写短评内容并提交。
修改：点击自己标记的点，修改短评内容，点击提交。
撤销：点击自己标记的点，弹出短评框，点击撤销按钮。
查看标点状态：点击自己标记的点，弹出短评框，顶部显示待审核，×掉短评框。

其他用户查看：地图显示各种颜色的圈，鼠标移上去显示圈对应的短评。

4. 处理
判断用户是否点击标记工具触发标记功能，若触发则在图中画圈，若非触发则只有浏览功能，鼠标指向圈弹出对应短评，若为自己的短评，则可以有特效区分，点击进行编辑撤销查看状态等。
//附下图参考，历史标点记录酌情添加，图例位置也可在顶部。
![image](https://github.com/JX3BOX/pvp/assets/32256957/7b5d431e-7318-4e94-a542-a9ea59b42ccd)

**Comment by X3ZvaWQ** [comment]
【吃鸡地图点位文档】
这个功能的数据表结构为
![image](https://github.com/JX3BOX/pvp/assets/47066861/e62f2608-d2d0-492b-94e6-0feced3d8bf6)
其中
![image](https://github.com/JX3BOX/pvp/assets/47066861/f60deca4-fe08-4326-9632-db24b3411e45)

为接口接收的参数，其他的会自动维护
公开接口只会返回status=1的数据
更新点位数据的时候会把status重新置为0需要再次审核

具体接口url可以参照
https://cms.jx3box.com/documentation#/

到时候写上swagger更方便
至于点位的评论，可以考虑直接使用我们网站的评论接口，烟姐安排了做审核功能
但是可能会需要单独写一个评论的组件去适配（？
