### ISSUE TITLE
【武学研习】技能音效

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvp#4]
1. 原始表 https://docs.qq.com/sheet/DSnNKTXlaVEtiS2Rs?tab=nnuhcs
2. 导出csv，转为json，5.json
3. 通过脚本处理现在的语音文件   [ jx3-audio](https://github.com/JX3BOX/jx3-audio)
4. 前端
<img width="163" alt="image" src="https://user-images.githubusercontent.com/8476969/233684784-5845ee8b-efee-4044-9266-9da62a51ad83.png">

/indexes/1.json
/voice/1/~~~~

**Comment by iRuxu** [comment]
<img width="247" alt="image" src="https://user-images.githubusercontent.com/8476969/233980478-1fba485d-c610-4bba-a8eb-a4f9e17515b0.png">

**Comment by ghn9264** [comment]
自定义录音上传
