### ISSUE TITLE
绝境战场问题II

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvp#46]
## Layouts
独立一个AppLayout，参考百战

整体背景黑色，下面tooltip也使用黑色背景
<img width="281" alt="image" src="https://github.com/JX3BOX/pvp/assets/8476969/3e50c273-b812-4774-8303-2b8923db9ea9">

- [x] 已完成

**Comment by iRuxu** [comment]
## 地图
<img width="496" alt="image" src="https://github.com/JX3BOX/pvp/assets/8476969/03441339-9543-48c9-8c4f-8c99bb3cff46">
```
border-radius: 3px;
    border: 10px solid #faebcc;
```

- [ ] 已完成

**Comment by iRuxu** [comment]
## 新版UI
<img width="1818" alt="image" src="https://github.com/JX3BOX/pvp/assets/8476969/e0d063db-048b-4cbe-a8da-9c3b3ee5975c">

1. 左上角的心法切换是正式服和怀旧服都要
2. 左上角的心法特殊加成，仅正式服有，需要不咕给接口
3. 左下角的装备需要醉栩出一套新的接口，然后2个运营指定好内容。
4. 左下角的技能查询仅怀旧服有，记得联动左上角的心法切换
5. 右上角为信息
6. 右下角为2个切换：标点，攻略；攻略的ui要极简化（头像 + 标题 + 时间）

- [ ] 已完成

**Comment by ghn9264** [comment]
> ## 新版UI
> <img alt="image" width="1818" src="https://user-images.githubusercontent.com/8476969/273596945-e0d063db-048b-4cbe-a8da-9c3b3ee5975c.png">
> 1. 左上角的心法切换是正式服和怀旧服都要
> 2. 左上角的心法特殊加成，仅正式服有，需要不咕给接口
> 3. 左下角的装备需要醉栩出一套新的接口，然后2个运营指定好内容。
> 4. 左下角的技能查询仅怀旧服有，记得联动左上角的心法切换
> 5. 右上角为信息
> 6. 右下角为2个切换：标点，攻略；攻略的ui要极简化（头像 + 标题 + 时间）
> 
> * [ ]  已完成

装备对比/技能拾取/道具介绍

调用物品百科接口，把吃鸡相关的道具放到道具介绍下面。
