### ISSUE TITLE
绝境战场功能补

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/pvp#52]
## 左下角：道具介绍
https://github.com/JX3BOX/pvp/issues/50

<img width="1818" alt="image" src="https://github.com/JX3BOX/pvp/assets/8476969/e0d063db-048b-4cbe-a8da-9c3b3ee5975c">

- [x] 已完成

**Comment by iRuxu** [comment]
## 左下角：装备对比

- [ ] 已完成

**Comment by iRuxu** [comment]
## Item组件迁移
可能要迁移一份vue3版本到jx3box-vue3-ui库

- [ ] 已完成

**Comment by X3ZvaWQ** [comment]
物品搜索接口新增参数
regexp - 正则搜索物品名称
startsWith - 搜索以**开头的物品
endsWith - 搜索以**结尾的物品

`https://node.jx3box.com/item/search?regexp=宿沙.*·曜`
`https://node.jx3box.com/item/search?startsWith=宿沙&endsWith=曜`

**Comment by iRuxu** [comment]
## 左上角
最好通过设置面包屑或菜单组
然后调用实现

- [ ] 已完成

**Comment by iRuxu** [comment]
## 怀旧服
只有怀旧服有左下角的技能？
怀旧服没有左上角的心法加成？（可以内容留空）

- [ ] 已完成
