### ISSUE TITLE
pvp模块一些建议

### ISSUE THREAD

**Issue by M-ls** [JX3BOX/pvp#66]
1.bug
目前切换到数据缺失的心法后，再切换别的心法，奇穴模拟器渲染丢失
复现：云裳心经－山海心诀－云裳心经
![Screenshot_2023-11-02-02-32-40-517_com miui home](https://github.com/JX3BOX/pvp/assets/36070993/71b0b40d-c613-4b02-b154-004cdf57ef31)

2.数据结构混乱
2.1部分数据复用bps仓库文件，需要赛季维护的门派数据和很少修改的吃鸡地图数据在同一个文件夹，没有一个统一的维护管理
建议：bps和pvp复用的门派数据迁移至oss/cdn统一维护，如无法实现也可将门派数据和吃鸡地图数据文件拆分文件夹，并记录维护文档
存疑：public发布pvp套路时心法数据缺失会报错，报错地方引用了哪部分数据？
2.2天赋模拟器版本非最新
取index的最新版本

3.吃鸡地图
大量物资和少量物资的图标大小有歧义，少量物资的图标看起来更大

**Comment by iRuxu** [comment]
1. 等不咕弄（11月第4周）
2. 同上，部分需求没看懂
3. 这个你和陆吾商量下，然后可以给冰块那边提
